#!/usr/bin/env python
import argparse
import sys
import os.path
import subprocess

parser = argparse.ArgumentParser(description='Check output file against expected result.')
parser.add_argument('size', type=int, default=1024,
                   help='the size of the input')
parser.add_argument('seed', type=int, default=1337,
				   help='random number generator seed')
parser.add_argument('file', type=str, 
				   help='output file')

args = parser.parse_args()
__dir__ = os.path.dirname(os.path.realpath(__file__))

try:
	subprocess.check_call(
		[os.path.join(__dir__, "../utilities/data"), 
			str(args.size), 
			str(args.seed),
			"--checkoutputfile",
			args.file
		], stdout=sys.stdout, stderr=sys.stderr)
	sys.exit(0)
except subprocess.CalledProcessError as e:
	sys.exit(e.returncode)


